//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOSSWORKLOG.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblClient
    {
        public int ClientId { get; set; }
        public string ShortName { get; set; }
        public string ClientName { get; set; }
        public string Email { get; set; }
        public string Contact { get; set; }
    }
}
