//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOSSWORKLOG.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMenu
    {
        public int Id { get; set; }
        public string MainId { get; set; }
        public string SubId { get; set; }
        public string Lable { get; set; }
        public string Action { get; set; }
        public string Controller { get; set; }
        public string Area { get; set; }
        public string IconClass { get; set; }
        public string UserRole { get; set; }
        public Nullable<int> SerialNo { get; set; }
        public Nullable<bool> IsSub { get; set; }
    }
}
